### ISSUE TITLE
Article title and url missmatch

### ISSUE THREAD

**Issue by cybergipsy2020** [Plume-org/Plume#809] opened 2020-08-04 05:09 UTC
I noticed that after I have saved a draft on Plume, later if I change the title when publishing this draft, the link inside the toot of this article in mastodon still uses the old title, thus making the link broken. Is this a Plume problem?

---

To be clear, I tested a few scenarios:
1. publish an article with title1 and then later change to title2 and publish it again

- the title of the article in plume: title2
- ending part of the url in plume: title1
- the title of the article in mastodon( from an account that follows this plume account): title1
- ending part of the url in mastodon: title1

2. save a draft with title5 and then later change to title6 and publish the article
- the title of the article in plume: title6
- ending part of the url in plume: title6
- the title of the article in mastodon: title6
- ending part of the url in mastodon: title5

- **Plume version:** You can find it in the footer of your instance. If you know the exact commit, please also add it.
0.4.0, installed from docker
- mastodon verision:
3.2.0
- **Operating system:**
- **Web Browser:**

**Comment by elegaanz** [comment] 2020-08-08 13:52
This is by design: see https://github.com/Plume-org/Plume/issues/207

However, we could probably make the solution better with https://github.com/Plume-org/Plume/issues/296 so I'm closing as a duplicate.

**Closed** 2020-08-08 13:52 UTC
Labels: C: Bug, S: Duplicate
