### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by fdb-hiroshima** [Plume-org/Plume#32] opened 2018-05-20 16:26 UTC
On page /@/<user> ,  the link to followers is pointing to /@/followers instead of /@/<user>/followers

**Comment by BaptisteGelez** [comment] 2018-05-21 17:37
Closing as a duplicate of #13, see https://github.com/Plume-org/Plume/pull/33#pullrequestreview-121882541

**Closed by BaptisteGelez** 2018-05-21 17:37 UTC
Labels: C: Bug, P: High, S: Duplicate
