### ISSUE TITLE
Notification do not show in firefox after v0.6.1-dev

### ISSUE THREAD

**Issue by pullopen** [Plume-org/Plume#839] opened 2021-01-16 18:24 UTC
Notification do not show anymore after v0.6.1-dev in Firefox, while in Chrome it shows normally. Open it and it just turns out as a blank page.

Browser default language is Chinese.

- **Plume version:** v0.6.1-dev
- **Operating system:** Windows 10
- **Web Browser:** Firefox

**Comment by KitaitiMakoto** [comment] 2021-01-17 14:03
hmm... I couldn't reproduce this problem. Can you tell me git commit hash you built?

> Open it and it just turns out as a blank page.

Did you mean neither Plume logo, title nor page title are shown?

**Comment by KitaitiMakoto** [comment] 2022-01-08 12:34
@pullopen  There was a bug. It should be fixed at the latest source code and Docker image.

**Closed** 2022-05-21 08:15 UTC
Labels: C: Bug
