### ISSUE TITLE
Feature request: single user mode

### ISSUE THREAD

**Issue by jeroenpraat** [Plume-org/Plume#241] opened 2018-09-20 22:02 UTC
Right now Plume is aimed towards multiple users on one instance. It would be great if there's a single user mode.

This would actually mean that the root of the (sub)domain (https://blog.example.com) would show a specific blog instead of Plume's landing page.

Plume version (and/or commit): 0.2.0

**Comment by BaptisteGelez** [comment] 2018-09-21 17:26
Hello!

I consider this issue a duplicate of #94, please re-open if what the implementation I proposed there is not correctly covering your use case.

**Closed by BaptisteGelez** 2018-09-21 17:26 UTC
