### ISSUE TITLE
clicking 'publish' on a new post leaves the post as draft at 732f514

### ISSUE THREAD

**Issue by khimaros** [Plume-org/Plume#495] opened 2019-03-21 02:49 UTC
1) create a new blog
2) create a new post and click "publish"
3) note that the state of the post is still "draft"

- **Plume version:** commit 732f514
- **Operating system:** Debian 10
- **Web Browser:** Chromium

**Comment by BaptisteGelez** [comment] 2019-03-21 09:28
This bug is normally fixed in #486

**Comment by fdb-hiroshima** [comment] 2019-04-06 17:26
Closing as #486 got merged, feel free to reopen if the issue is still here

**Closed by fdb-hiroshima** 2019-04-06 17:26 UTC
Labels: C: Bug
