### ISSUE TITLE
No way to embed a picure uploaded to the gallery

### ISSUE THREAD

**Issue by MrSoUndso** [Plume-org/Plume#474] opened 2019-03-12 18:30 UTC
Once you have uploaded a picture to the gallery, the user gets prompted with a page showing him the picture itself and a markdown code to embed the picture into a blog, but once the user leaves this page, they cannot get back to it, because of the images in the gallery not being clickable. This results in the user being unable to use the pictures uploaded to the gallery, except as the Illustration, which is selectable in the drop-down menu below a post.

Plume version (and/or commit):
0.2.0

**Comment by BaptisteGelez** [comment] 2019-03-12 18:39
Did you wrote a description for your image? Normally, if you did, it should show next to the image in the gallery and be clickable. But the gallery interface was quite horrible before #452 (which is probably not yet deployed on your instance).

**Comment by MrSoUndso** [comment] 2019-03-12 19:08
The instance I'm using is https://fediverse.blog/ if this helps.

**Comment by BaptisteGelez** [comment] 2019-03-12 19:11
OK, thanks. As I said in #475 I'm currently updating it. I will tell you once it's done, so that you can check the issue is indeed fixed, but I checked in the code and normally it should be: there a now a "Details" link for each image that is always visible.

**Comment by BaptisteGelez** [comment] 2019-03-12 19:49
@MrSoUndso It should be fixed now. Can you please confirm?

**Comment by BaptisteGelez** [comment] 2019-03-15 15:07
I think we can consider this as resolved. If the issue is not actually fixed, please tell us.

**Closed by BaptisteGelez** 2019-03-15 15:07 UTC
Labels: A: Front-End, C: Bug, P: High
