### ISSUE TITLE
Spaces in usernames seem to prevent federation

### ISSUE THREAD

**Issue by Shutsumon** [Plume-org/Plume#435] opened 2019-01-24 03:11 UTC
This is the first time I have created an issue for anything so I hope I do this right.

I have a plume account here: https://plume.mastodon.host/@/Firebird%20Fiction/ and I rather foolishly created it with a space in the username.

This seems to prevent me from finding my account from my mastodon account https://tootplanet.space/@Shutsumon in order to follow it although I can find other plume.mastodon.host accounts. Also while II can find my masto account and apparently follow it from my plume account but then nothing happens... no toots appear and I don't get a message saying I've been followed over on tootplanet.

I would suggest either preventing spaces in usernames or finding a way to represent the space. 

Plume version (and/or commit):

**Comment by fdb-hiroshima** [comment] 2019-01-24 12:08
There is no need to fill an issue with Mastodon, they won't consider it a bug, and are probably right.
Spaces, and a few other characters, have been forbidden in usernames since #386 landed (2018-12-25), either you account is older than that or mastodon.host is not up to date, but there is not much we can do to help.

**Comment by BaptisteGelez** [comment] 2019-01-24 12:13
Yes, plume.mastodon.host is not very up-to-date I think. Maybe you could try to contact your admin about it (or I can do it if you want).

**Comment by Shutsumon** [comment] 2019-01-26 17:36
Thanks, I'll look up the admin and drop them a line :-)

**Comment by BaptisteGelez** [comment] 2019-03-12 13:41
I'm closing this, since the issue is fixed on ur side.

**Closed by BaptisteGelez** 2019-03-12 13:41 UTC
